# ==========================================
# CONFIGURACION SONARQUBE - CONTEX360 BACKEND
# ==========================================

# Clave del proyecto
sonar.projectKey=contex360-backend

# Nombre del proyecto
sonar.projectName=Contex360 Backend

# Version
sonar.projectVersion=1.0

# Ruta de los sources
sonar.sources=src

# Inclusiones
sonar.inclusions=**/*.ts,**/*.js,**/*.json

# Exclusiones
sonar.exclusions=node_modules/**,dist/**,build/**,**/*.spec.ts,**/*.test.ts,coverage/**

# Codificacion
sonar.sourceEncoding=UTF-8

# Host de SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticacion
sonar.token=sqa_a576875b127c6a6a8b7dc35141bd09dd230bfe7e

# Lenguaje
sonar.language=ts

# ==========================================
# COBERTURA DE CODIGO (Para pasar a verde)
# ==========================================
# Ruta al reporte de cobertura generado por Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Incluir archivos de test en el analisis
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Excluir archivos de configuracion y tests del analisis de codigo
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,vitest.config.ts,**/*.spec.ts,**/*.test.ts
